### ISSUE TITLE
コントロールバーを常に表示した状態にしたい

### ISSUE THREAD

**Issue by Neos21** [1natsu172/Outside-YouTube-Player-Bar#36]
再生時間などを確認したく、コントロールバーを常に表示する設定があると嬉しいです。

**Comment by 1natsu172** [comment]
@Neos21 APIがなく、ハッキーな実装で一度チャレンジをしましたが以前に失敗しました。v3の開発でリトライする予定なので、約束はできませんが再チャレンジしてみます。

**Comment by 1natsu172** [comment]
@Neos21 v3でご要望をextensionの仕様としました。v3はストアへリリース済みです。
https://github.com/1natsu172/Outside-YouTube-Player-Bar/releases/tag/v3.0.0
