### ISSUE TITLE
[Feature Request] Disable Auto-Hiding Progress Bar

### ISSUE THREAD

**Issue by Deagan** [1natsu172/Outside-YouTube-Player-Bar#37]
Awesome tweak, do you think you could add an option to keep the Progress Bar active instead of auto-hiding it? I would like it to stay visible so that it doesn't animate the rest of the page elements, and keeps everything static!

**Comment by eggplants** [comment]
+1

**Comment by wooshaq** [comment]
I would also be glad to see that added!

**Comment by 1natsu172** [comment]
> stay visible

umm, YouTube doesn't provide that api. I'll try but I can't make any promises.

> doesn't animate the rest of the page elements

planning to change v3 due to many requests.

**Comment by 1natsu172** [comment]
@Deagan @wooshaq 
Implementation of v3 is complete.
Due to many requests, the playback bar will always be displayed from the next version. In other words, the playback bar is always visible when it is outside.

The v3 is currently under store review, so please wait a little longer.

**Comment by 1natsu172** [comment]
v3 is already available now.

close https://github.com/1natsu172/Outside-YouTube-Player-Bar/releases/tag/v3.0.0
