### ISSUE TITLE
On 3.0 edge open in a popup button is not shown. Any chance to fix this?

### ISSUE THREAD

**Issue by wooshaq** [1natsu172/Outside-YouTube-Player-Bar#41]
![Bez nazwy-1](https://user-images.githubusercontent.com/33185960/178826159-e506cba5-8313-4119-aa25-4d7eb82167ef.png)
I used Permament Prograss Bar For Youtube extension for now and it works fine with edge but I really would love to switch to your extension as it shows chapters on the progress bar, but on edge there is this picture in picture button that appears when you hver the mouse over the video but with your extension on the button is no longer there, could you investigate it please?

**Comment by 1natsu172** [comment]
@wooshaq 
![スクリーンショット 2022-07-18 19 21 00](https://user-images.githubusercontent.com/7282145/179492327-da527068-2bd1-4e4e-b06a-54150b4ad6cb.png)

This is a bug in edge, not in this extension. It seems that the PiP button sometimes disappears for some reason, and once this happens, the only way to fix it is to duplicate the tab again.
