### ISSUE TITLE
Video Title and upper player icon present when in fullscreen mode

### ISSUE THREAD

**Issue by wishyu** [1natsu172/Outside-YouTube-Player-Bar#42]
Hello, I have been enjoying using this extension as I am able to see the video without the overlay when pausing and resuming playback. With the latest change in version 3.0.0, when the player bar is placed outside it is always present to avoid the page elements from moving so much. Though with this, I have been having problems when using this extension in fullscreen mode.
<br>
![image](https://user-images.githubusercontent.com/32516842/180366697-195889de-cb42-4e28-9c34-7151589e8122.png)

> When the video is in fullscreen mode and the player bar is placed outside the video title, watch later, and share icons are present and would not disappear. 
<br>
Perhaps having the player bar placed inside when in fullscreen mode would be possible?

**Comment by 1natsu172** [comment]
@wishyu Thanks for  making issue. I had not noticed this problem in full screen in my environment.

So, it's uncertain if I can fix it right away, but for once, to make the player bar inside when in full screen, scroll down the screen and press this extension button on the player bar. Inside mode. That will return you to the default YouTube behavior.

**Comment by 1natsu172** [comment]
@wishyu  Bug fixed. An update will be applied soon.
