### ISSUE TITLE
The control bar disappears

### ISSUE THREAD

**Issue by kesera2** [1natsu172/Outside-YouTube-Player-Bar#44]
Hi there. Thanks for providing a nice chrome extension.
When I watch youtube, the control bar disappears when this extension is enabled.

<img width="1227" alt="image" src="https://github.com/1natsu172/Outside-YouTube-Player-Bar/assets/38027941/f7958dc1-4ba9-479c-941e-0791d76ff117">

Chrome version: 116.0.5845.96（Official Build） （arm64）

**Comment by rsyqvthv** [comment]
same issue here, any solution? thanks.

**Comment by 1natsu172** [comment]
@kesera2 @rsyqvthv 
I have checked the issue. I will try to fix it.

**Comment by rsyqvthv** [comment]
Thank you. :)

**Comment by 1natsu172** [comment]
@rsyqvthv @kesera2 
I have released v.3.0.2. It has already shipped to store.

**Comment by rsyqvthv** [comment]
Thanks for your updating, but the last version still disappeases when I click somewhere around comments in desktop, I am using the 3.0.3 version. would you please double check it? thanks.

**Comment by 1natsu172** [comment]
@rsyqvthv
OK, as you said, clicking near the comment confirmed the problem. I will try to fix it.

**Comment by 1natsu172** [comment]
@rsyqvthv I have released v3.0.4. The issue should be resolved as we have addressed the problem.

**Comment by rsyqvthv** [comment]
thanks for your updating, I've tested and confirm that the bar is stick where it should be. :)

but I found it have quite bit more cpu drain, I will raise another issue for that.
