### ISSUE TITLE
コントロールバーが表示されない問題の解決策

### ISSUE THREAD

**Issue by IRespectAkari** [1natsu172/Outside-YouTube-Player-Bar#56]
以前にも上がっていたようですが、現在コントロールバーが表示されませんでした。
既にお気づきでしたらすみません。
自分なりに色々調べたり拡張機能の「Stylebot」や検証機能で試行錯誤してみた結果、恐らくですがz-indexが親要素によって制限されているのではないのかと思われました。
[CSSでz-indexが効かない時の4つの原因とその対応方法 | コリス](https://coliss.com/articles/build-websites/operation/css/4-reasons-z-index-isnt-working.html)の4つ目の原因が今回の問題点なのではないかと思っています。
コントロールバーが動画の子要素で、動画がページの子要素なので、コントロールバーのz-indexを999999にしてもあくまで「aria-label="YouTube 動画プレーヤー"」内で最前面になるだけで、隠れてしまいます。
そこで親要素である#movie_playerにposition: absolute;又はposition: fixed;を「Stylebot」や「検証機能」にて追加したところ、今までどおり働きました。
再生バーの内外入れ替えも出来ます。
ただ唯一、出来なくなるのはミニプレーヤーにしたときに不自然に再生画面が下がる事です。
そのためミニプレーヤー時の一部操作やボタン等が見られなくなります。
absoluteよりもfixedの方が不自然さが大きくなります。
もし何か手助けになれば幸いです。

**Comment by 1natsu172** [comment]
@IchikawaAkari 当拡張機能の問題か、YouTube側のABテストか、個々人の環境差異かわからないため以下の情報をご提示ください。

1. 再現する動画のURL
2. 現象発生時の **画面全体の** スクリーンショットもしくは動画
3. Chromeのシークレットモードにて他の拡張機能を一切インストールせず、当拡張機能のみインストールした状態での動作状況

**Comment by 1natsu172** [comment]
ちなみに当方ではどの環境どのアカウントにおいても現行v3.0.5では正常動作するため、Issueの再現が取れておりませんので対応できることがない状態になります。

**Comment by 1natsu172** [comment]
シネマモードでは再現しないがデフォルト表示で再現することがわかりました。
