### ISSUE TITLE
Not working on youtube.com/[@username/live] addresses

### ISSUE THREAD

**Issue by thegr812k** [1natsu172/Outside-YouTube-Player-Bar#59]
troubleshooted below...

**Comment by thegr812k** [comment]
UPDATE:

If using a live link such as : https://www.youtube.com/@TheIrishHotspur/live it does not work, but then if i go onto the channel and click the url it works :https://www.youtube.com/watch?v=RMTl3Han_qY&ab_channel=TheIrishHotspur

When there is a "@username" after the .com it doesnt work. Ive tested with multiple channels and can replicate. You just need to find a live feed for your own testing (as this channel wont likely be live when you get this message). Then try the youtuve.com/@channelname/live and you will see it doesnt work. Then go into that channels page and click the live link direct and its fine

**Comment by thegr812k** [comment]
Noticed this bug in some other addons, simply updating the URL catcher has fixed it for them. Please do the same for this, thanks!

**Comment by thegr812k** [comment]
BUMP

**Comment by 1natsu172** [comment]
It seems that the operation on the Live page is unstable. Thank you for the report.
I'll fix it if I can, but it's a best effort.

**Comment by 1natsu172** [comment]
memo: 
- when direct access to live video page is not working
- works if the first step on the user channel and then navigate to the live page

**Comment by thegr812k** [comment]
Yes I can confirm it works when using main channel first . I save my bookmarks with /live so I can bulk connect to channels to see if they are streaming. Having this functionality would be great thanks

**Comment by 1natsu172** [comment]
@thegr812k
Fixed this issue and now store is under review. It usually takes 1-3 days to be distributed automatically if not rejected.

**Comment by thegr812k** [comment]
nope still dont work with /live on 3.09 - do you even test?
