### ISSUE TITLE
/live pages still not fixed after 3.08 update

### ISSUE THREAD

**Issue by thegr812k** [1natsu172/Outside-YouTube-Player-Bar#69]
previous bug was submitted to fix the bug of itn ot working when using /live in the url . Still not working

**Comment by 1natsu172** [comment]
Thanks for report. Umm, Youtube is sometimes change behavior. (Perhaps an AB test?) 

When I debugged it a few days ago,  `/live` was redirected to `/watch` in my environment, but now it is not.

I will look into a different implementation for `/live`. Best effort.

**Comment by 1natsu172** [comment]
ref #59

**Comment by 1natsu172** [comment]
Quick patch for fix v3.0.9.
It will be distributed after review in a few days. If this doesn't fix the problem, it's difficult to fix it right away because the problem is deep-rooted.
