### ISSUE TITLE
https://www.youtube.com/*CHANNEL NAME**/live does not work

### ISSUE THREAD

**Issue by thegr812k** [1natsu172/Outside-YouTube-Player-Bar#71]
I can see you have attempted a fix and can see that what you have changed but i think you misunderstood the issue.

Its when the URL is in this format:

https://www.youtube.com/*CHANNEL NAME**/live

EG: https://www.youtube.com/sameoldarsenal/live

You appear to have fixed it when the format is:

https://www.youtube.com/watch?v=hRVvwTEQHhk/live

NOTE - these examples will only work if that channel is live when you are testing.

You need to find a channel which is currently live -> go to channel homepage and add /live to the URL and then test

**Comment by 1natsu172** [comment]
I'm not misunderstanding this issue.
This is a bug due to YouTube's URL pattern being different depending on the user account.

@username/live
username/live
And there seems to be a pattern that redirects these to each other.

**Comment by 1natsu172** [comment]
Fixed by next ver. Now under review in store.
